### ISSUE TITLE
Will there be sass support?

### ISSUE THREAD

**Issue by Spoki4** [Grimones/vscode-styled-jsx-languageserver#4]
Do you plan to support Sass, using a styled-jsx with a sass plugin? Displays errors when using nested selectors.

**Comment by Grimones** [comment]
Unfortunately it is not possible for now, as the extension is using css language server from vscode. This extension just extracts text from `<style jsx>`  tags and gives it to vscode css language server. 

So, what vscode supports for css out of the box - this extension supports too. 
I believe that SCSS should work, but i haven't tested.

I'm closing this for now, may be vscode will support Sass some day

**Comment by u3u** [comment]
@Grimones 
Hello, you can refer to [this file](https://github.com/vuejs/vetur/blob/4bfd6f3a327a2f64d2afeb99df5f962cd6472274/server/src/modes/style/index.ts), `vscode-css-languageservice` contains CSS, SCSS and LESS services. I tried to modify line 59 in `~/.vscode/extensions/AndrewRazumovsky.vscode-styled-jsx-languageserver-1.0.1/server/out/styled-jsx-server-main.js` to replace `getCSSLanguageService` with `getLESSLanguageService` Then reload the window to get it to work!


```diff
- var cssLanguageService = vscode_css_languageservice_1.getCSSLanguageService();
+ var cssLanguageService = vscode_css_languageservice_1.getLESSLanguageService();
```

Hopefully the author has time to improve this problem, it can help more people!

---

Maybe we need to agree on the format, for example refer to [vetur](https://github.com/vuejs/vetur):

```jsx
<style jsx>{`
  /* css language service */
`}</style>
```

```jsx
<style jsx lang="less">{`
  /* less language service */
`}</style>
```

```jsx
<style jsx lang="sass">{`
  /* scss/sass language service */
`}</style>
```
